#defaultMarkdownHandler = "goldmark"

[tableOfContents]
endLevel = 5
ordered = true
startLevel = 2
[goldmark]
#[goldmark.extensions]
#definitionList = true
#footnote = true
#linkify = true
#strikethrough = true
#table = true
#taskList = true
#typographer = true
#[goldmark.parser]
#autoHeadingID = true
#autoHeadingIDType = "github"
#[goldmark.parser.attribute]
#block = true
#title = true
[goldmark.renderer]
#hardWraps = false
unsafe = true
#xhtml = false

#[highlight]
#style = "trac"
#lineNumbersInTable = true
#noClasses = false

