#disableCSS = true
#disableHTML = true
#disableJS = true
#disableJSON = true
#disableSVG = true
#disableXML = true
#minifyOutput = true
#[tdewolff]
#[tdewolff.css]
#keepCSS2 = true
#precision = 0
#[tdewolff.html]
#keepComments = false
#keepConditionalComments = true
#keepDefaultAttrVals = true
#keepDocumentTags = true
#keepEndTags = true
#keepQuotes = false
#keepWhitespace = false
#[tdewolff.js]
#keepVarNames = false
#precision = 0
#[tdewolff.json]
#precision = 0
#[tdewolff.svg]
#precision = 0
#[tdewolff.xml]
#keepWhitespace = false