[build]
publish = "public"
#command = "hugo --gc"

[context.production.environment]
HUGO_VERSION = "v0.107.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview.environment]
HUGO_VERSION = "v0.107.0"
HUGO_ENV = "deploy-preview"
HUGO_ENABLEGITINFO = "true"

[context.branch-deploy.environment]
HUGO_VERSION = "v0.107.0"
HUGO_ENV = "branch-deploy"
HUGO_ENABLEGITINFO = "true"