name: Hugo-CI
on:
  push:
    branches: [ main ]
    paths-ignore:
      '.github/**'

jobs:
  job-deploy:
    name: Deploy
    runs-on: [self-hosted, linux, x64, dev4-svg]
    steps:
      - name: preparing workspace git pull documentation
        run: |
          cd ${{secrets.HUGO_SITE_LOCATION}}
          pwd
          ls -lA
          git fetch
          git reset --hard origin/main
      - name: preparing workspace clean public folder
        run: |
          cd ${{secrets.HUGO_SITE_LOCATION}}
          pwd
          ls -lA
          sudo rm -rf public
          ls -lA

      - name: hugo build
        run: |
          cd ${{secrets.HUGO_SITE_LOCATION}}
          ./bin/hugo mod tidy
          ./bin/hugo mod graph
          ./bin/hugo mod verify
          ./bin/hugo version
          # hugo --minify --baseURL https://docs.aspose.com/html
          #  sudo ./bin/hugo -c content --debug --log --print-mem --templateMetrics --minify -v --baseURL https://docs.aspose.com/svg
          sudo ./bin/hugo -c content --log --minify -v --baseURL https://docs.aspose.com/svg
          rsync --recursive --delete --force -e "ssh" --progress public/ ${{ secrets.TRANSFERPATH }}
      - name: hugo deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.SSHPORT }}
          script: |
            sudo rsync --recursive --delete --force --progress ${{ secrets.PUBLICCONTENTPATH }} ${{ secrets.DEPLOYPATH }}
            sudo nginx -s reload